name: trading-python

services:
  py-layer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # Publish only if you want host access. For internal-only, remove 'ports:'
    ports:
      - "${PY_LAYER_HOST_PORT}:8080"

    restart: unless-stopped
    networks:
      core:
        aliases: [trading-py]

networks:
  core:
    external: true
    name: trading-core
